name: cart-service
on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/cart.yaml'
  pull_request:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/cart.yaml'

jobs:
  cart:
    name: Build and Deploy Cart Microservice
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'   # use 18 or 20 (LTS), not 24

      - name: Install Dependencies
        run: |
          cd cart
          npm install

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cart:v ./cart

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cart:v
